# Generated by Django 5.2.6 on 2025-09-28 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0006_alter_feedback_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booktable',
            old_name='Total_perdon',
            new_name='Total_person',
        ),
    ]
