# Generated by Django 5.2.6 on 2025-10-10 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0010_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='orders/'),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
