# Generated by Django 5.2.6 on 2025-10-10 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0012_order_food_items_alter_order_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FoodItem',
        ),
        migrations.AlterField(
            model_name='booktable',
            name='Phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='order',
            name='food_items',
            field=models.ManyToManyField(related_name='orders', to='Base_App.items'),
        ),
    ]
