# Generated by Django 5.2.6 on 2025-10-10 15:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0013_delete_fooditem_alter_booktable_phone_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='image',
        ),
        migrations.AlterField(
            model_name='items',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='Base_App.itemlist'),
        ),
    ]
