# Generated by Django 5.2.6 on 2025-10-11 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Base_App', '0015_fooditem_order_image_alter_booktable_phone_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
